[build]
  command = "pip install 'fastapi[standard]' && fastapi run"
  publish = "."

[context.production]
  command = "fastapi run"

[context.main]
  command = "fastapi run"

[functions]
  directory = "functions" # Point to where your handler is located
