[build]
  command = "pip install -r requirements.txt"
  publish = "public" # This can be an empty folder if you have no frontend

[functions]
  directory = "functions" # Point to where your handler is located
